# Generated by Django 3.1 on 2022-01-26 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='created_user',
            field=models.TextField(),
        ),
    ]
