# Generated by Django 3.1 on 2022-01-27 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proposal', '0002_auto_20220126_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='created_user',
            field=models.ForeignKey(db_column='created_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
