# Generated by Django 3.1 on 2022-03-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_reset_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_token_expire_time',
            field=models.DateTimeField(null=True),
        ),
    ]
