# Generated by Django 3.1 on 2022-03-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_reset_password_token_expire_time'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
