# Generated by Django 3.1 on 2022-02-17 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0004_auto_20220216_0335'),
        ('classes', '0001_initial'),
        ('problem', '0002_auto_20220216_0140'),
        ('contest', '0002_auto_20220216_0046'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('score', models.FloatField()),
                ('csv', models.FileField(blank=True, null=True, upload_to='')),
                ('ipynb', models.FileField(blank=True, null=True, upload_to='')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.TextField(null=True)),
                ('on_leaderboard', models.BooleanField(default=False)),
                ('c_p_id', models.ForeignKey(blank=True, db_column='c_p_id', on_delete=django.db.models.deletion.CASCADE, to='contest.contest_problem')),
                ('class_id', models.ForeignKey(blank=True, db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='classes.class')),
                ('competition_id', models.ForeignKey(blank=True, db_column='competition_id', on_delete=django.db.models.deletion.CASCADE, to='competition.competition')),
                ('problem_id', models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, to='problem.problem')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
