# Generated by Django 3.1 on 2022-02-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='score',
            field=models.FloatField(null=True),
        ),
    ]
