# Generated by Django 3.1 on 2022-02-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20220218_0225'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='submissionclass',
            table='submission_class',
        ),
        migrations.AlterModelTable(
            name='submissioncompetition',
            table='submission_competition',
        ),
    ]
