# Generated by Django 3.1 on 2022-03-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_exam', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'contest',
            },
        ),
        migrations.CreateModel(
            name='Contest_problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('data_description', models.TextField()),
                ('order', models.IntegerField()),
                ('contest_id', models.ForeignKey(db_column='contest_id', on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
            ],
            options={
                'db_table': 'contest_problem',
            },
        ),
    ]
