# Generated by Django 3.1 on 2022-02-16 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
        ('classes', '0001_initial'),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_problem',
            name='problem_id',
            field=models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, to='problem.problem'),
        ),
        migrations.AddField(
            model_name='contest',
            name='class_id',
            field=models.ForeignKey(db_column='class_id', on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='contests', to='contest.Contest_problem'),
        ),
    ]
