# Generated by Django 3.1 on 2022-03-27 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestproblem',
            name='problem_id',
            field=models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problem.problem'),
        ),
    ]
