# Generated by Django 3.1 on 2022-02-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
