# Generated by Django 3.1 on 2022-03-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
