# Generated by Django 3.1 on 2022-02-16 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='problem_id',
            field=models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, to='problem.problem'),
        ),
        migrations.AddField(
            model_name='competition',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='competition', to='competition.Competition_user'),
        ),
    ]
