# Generated by Django 3.1 on 2022-02-06 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0001_initial'),
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='problem_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='problem.problem'),
        ),
        migrations.AddField(
            model_name='competition',
            name='users',
            field=models.ManyToManyField(through='competition.Competition_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
