# Generated by Django 3.1 on 2022-03-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition', '0001_initial'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='problem_id',
            field=models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, to='problem.problem'),
        ),
    ]
