# Generated by Django 3.1 on 2022-02-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_auto_20220216_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='competition', to='competition.Competition_user'),
        ),
    ]
