# Generated by Django 3.1 on 2022-02-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='contests',
            field=models.ManyToManyField(blank=True, null=True, through='problem.Contest_problem', to='contest.Contest'),
        ),
    ]
