# Generated by Django 3.1 on 2022-02-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='class_id',
            field=models.ForeignKey(blank=True, db_column='class', null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
        migrations.AddField(
            model_name='problem',
            name='evaluation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
