# Generated by Django 3.1 on 2022-03-07 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='professor',
            field=models.ForeignKey(blank=True, db_column='professor', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_professor', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
