# Generated by Django 3.1 on 2022-02-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
