# Generated by Django 3.1 on 2022-03-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20220329_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='title',
            field=models.TextField(error_messages={'unique': '중복된 제목 입니다.'}, unique=True),
        ),
    ]
